# See https://github.com/devcontainers/ci/blob/main/docs/github-action.md

name: 'build'
on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # See https://github.com/devcontainers/ci/issues/191#issuecomment-1416384710
      - name: Install updated Skopeo
        # This can be omitted once runner images have a version of Skopeo > 1.4.1
        # See https://github.com/containers/skopeo/issues/1874
        run: |
            sudo apt purge buildah golang-github-containers-common podman skopeo
            sudo apt autoremove --purge
            REPO_URL="https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable"
            source /etc/os-release
            sudo sh -c "echo 'deb ${REPO_URL}/x${NAME}_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list"
            sudo wget -qnv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/x${NAME}_${VERSION_ID}/Release.key -O Release.key
            sudo apt-key add Release.key
            sudo apt-get update
            sudo apt-get install skopeo

      - name: Checkout (GitHub)
        uses: actions/checkout@main

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@master

      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@master
        with:
          use: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3.1900000349
        with:
          imageName: ghcr.io/aquaticat/monochromatic
          cacheFrom: opensuse/tumbleweed
          push: always
          platform: linux/amd64,linux/arm64

