# See https://github.com/devcontainers/ci/blob/main/docs/github-action.md

name: 'build'
on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@latest

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@latest

      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@latest
        with:
          use: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@latest
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@latest
        with:
          imageName: ghcr.io/aquaticat/monochromatic
          push: always
          platform: linux/amd64,linux/arm64
