# See https://github.com/devcontainers/ci/blob/main/docs/github-action.md

name: 'build'
on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * 0

jobs:
  build:
    # So that we can skip the time-consuming step of installing updated skopeo
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@main

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@master

      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@master
        with:
          use: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3.1900000349
        with:
          imageName: ghcr.io/aquaticat/monochromatic
          cacheFrom: opensuse/tumbleweed
          push: always
          platform: linux/amd64,linux/arm64

